services:
  traefik:
    container_name: traefik
    image: traefik:latest
    env_file:
      - env
    ports:
      - "80:80"
      - "443:443"
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "certs:/certs"
        - "./traefik.yml:/etc/traefik/traefik.yml"
        - "./dynamic.yml:/etc/traefik/dynamic.yml"
    restart: unless-stopped
    network_mode: "bridge"

volumes:
  certs:
