services:
  thelounge:
    image: thelounge/thelounge:latest
    container_name: thelounge
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thelounge.entrypoints=websecure"
      - "traefik.http.routers.thelounge.rule=Host(`lounge.example.com`)"
      - "traefik.http.routers.thelounge.tls.certresolver=cloudflare"
      - "traefik.http.routers.thelounge.middlewares=compression@file,cache-header@file,security-header@file"
      - "traefik.http.services.thelounge.loadbalancer.server.port=9000"
    volumes:
      - ./config.js:/var/opt/thelounge/config.js
      - data:/var/opt/thelounge
    restart: unless-stopped

volumes:
  data:

networks:
  traefik_proxy:
    external: true