services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ~/www/nginx:/www
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.rule=Host(`example.com`,`www.example.com`)"
      - "traefik.http.routers.nginx.tls.certresolver=cloudflare"
      - "traefik.http.routers.nginx.middlewares=compression@file,cache-header@file,security-header@file"
    restart: unless-stopped

networks:
  traefik_proxy:
    external: true